export const BASE_URL = "/api/"

export const FEED_MESSAGE = [
  "🕵️‍♂️ Nothing to see here... just a lonely feed waiting for love and server responses.",
  "🥲 Your feed is emptier than my fridge on a Sunday night.",
  "👀 Still loading... or maybe your feed just ghosted you.",
  "🤷‍♀️ No feed here. Maybe it's on a coffee break.",
  "🦗 Just crickets... and your thoughts echoing in here.",
  "📭 This feed is as empty as my motivation on Monday mornings.",
  "🧙‍♂️ Feed has vanished! Must be a bug... or a wizard.",
  "💾 If (feed === null) { panic(); }",
  "🚀 Waiting for data like it's a SpaceX launch... T-minus who knows.",
  "📡 Feed not found. Maybe it's stuck in a Git merge conflict.",
  "🕳️404: Feed not found. Try turning it off and on again?",
  "🧃 Still squeezing the data from the backend fruit. Stay juicy.",
  "🐒 Your feed ran off to join the circus. It'll be back… maybe.",
  "🦄 No feed here, but if you believe hard enough, one might appear.",
  "🥔 This feed is more empty than my brain during math class.",
  "🚫 Nothing here yet—unless you count my bad decisions.",
  "🪦 Your feed died of boredom. Please revive with new data.",
  "😼 Feed not found. A cat probably knocked it off the table.",
  "🐾 Your feed is hiding under the bed. Try luring it out with treats.",
  "🐱 No feed... but plenty of judgmental cat stares.",
  "🎮 Your feed failed to spawn. Try respawning it!",
  "🕹️ Feed loading... please insert more quarters.",
  "💣 Your feed was fragged. Game over. Try again?",
  "🪐 Your feed took a wrong turn at the multiverse.",
  "🧻 Still waiting for the backend to stop scrolling on TikTok.",
  "🍕 No feed, but hey—have a slice of pizza and chill.",
  "🧠 Feed empty. So is my ability to pretend everything’s fine.",
  "🦕 Still waiting... The data is being delivered by a polite dinosaur."
];

export const REQUESTS_MESSAGE = [
  "📭 No requests. Even the bots are ignoring you.",
  "👻 So quiet here, you'd think it was haunted.",
  "🧍 Just you and your perfectly symmetrical social life.",
  "🪞 Still waiting... but hey, at least you're popular with yourself!",
  "🚫 No new requests. Not even a scammer pretending to be a prince.",
  "🦗 It’s just you, the silence, and a cricket or two.",
  "📡 Broadcasting your vibes... no one's tuned in yet.",
  "💌 You’ve got... nothing. Zero. Zilch.",
  "🧊 Your inbox is chillier than the Arctic right now.",
  "👀 Nope, not even an accidental friend request.",
  "🎭 Everyone’s busy... pretending they didn’t see your profile.",
  "🪶 Your request list is lighter than a feather in space.",
  "📉 Your popularity graph just flatlined.",
  "🐕 Still no requests, but your dog would definitely connect with you.",
  "📵 All quiet on the request front. Social drought continues.",
  "💃 Waiting for invites like it's prom night all over again.",
  "🪑 This section is emptier than the last row at a Monday meeting.",
  "🎈 No connections yet, but look on the bright side: no drama either!",
  "🔍 We checked twice. Nope, still nobody reaching out.",
  "🎣 Throwing out social bait... still no bites.",
  "🛎️ Nobody's rung your social doorbell yet.",
  "🧃 No requests, but your vibe? Immaculate.",
  "🥹 Waiting for connection requests like it’s a text from your crush.",
  "📅 Marking another day in the calendar of 'No New Requests'.",
  "🧘 No requests. Just inner peace. And maybe mild concern."
];

export const CONNECTIONS_MESSAGE = [
  "🧍‍♂️ It’s just you here… but hey, you're great company.",
  "🤝 No connections yet, but the world is full of potential besties.",
  "📡 You’re broadcasting good vibes — just waiting on a reply.",
  "🦸‍♂️ Even heroes start their journey alone. Connections will come.",
  "🚶 No one's joined your journey yet, but the path is wide open.",
  "🪁 You’re flying solo — for now.",
  "🧊 Your connections are on ice. Warm them up with a few requests!",
  "🪞 Mirror time: your only connection is… yourself. And that’s deep.",
  "🛸 Still searching the galaxy for like-minded lifeforms.",
  "📖 Your connection story is a blank page. Time to write chapter one.",
  "🧙‍♀️ Alone, but with great power (and no notifications).",
  "🎨 Your social canvas is blank — start painting friendships!",
  "🥽 Exploring the friend zone... but like, literally alone.",
  "🍃 No connections yet — but you're totally giving main character energy.",
  "🔍 You haven’t connected with anyone, but someone might be watching 👀",
  "🪴 No connections, but you’re growing on your own. Respect.",
  "🎯 No connections, but your aim is true. Go make some noise!",
  "🏕️ You’re the first camper. The rest of the crew is coming soon.",
  "🚫 You haven’t added anyone yet. Let’s change that?",
  "🗺️ Your map is empty. Start exploring some profiles!",
  "📭 Connection inbox: Zero. Motivation to mingle: Hopefully increasing.",
  "🎢 Still at the beginning of your social rollercoaster.",
  "⏳ Just waiting for the connection stars to align.",
  "🎈 No one’s here yet, but at least the air is fresh."
];
